apiVersion: apps/v1
kind: Deployment
metadata: 
  name: my-deployment
  labels:
    app: myapp

spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp
  template: 
    metadata:
      name: tomcat-pod
      labels:
        app: myapp

    spec:
      containers:
        - name: tomcat
          image: giridaran/newapp
          ports:
          - containerPort: 8080


---

apiVersion: v1
kind: Service
metadata: 
  name: tomcat-sv

spec:
  type: NodePort
  ports:
  - targetPort: 8080
    port: 8080
    nodePort: 30780
  selector:
    app: myapp
